### ISSUE TITLE
How to wire-up JSON-RPC manually to a "source/conduit"

### ISSUE THREAD

**Issue by saurabhnanda** [xenog/json-rpc#4]
Not really an issue, but don't know where else to ask. Any help with http://stackoverflow.com/questions/35011946/how-to-wire-up-json-rpc-manually-to-a-source-conduit will be really appreciated.

**Comment by xenog** [comment]
Look at the examples. They should clarify how to do this. Read [this manual](https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/conduit-overview) if you still do not understand.
