### ISSUE TITLE
HTTP server example

### ISSUE THREAD

**Issue by anpryl** [xenog/json-rpc#5]
Hello
Can you please provide example with http json-rpc server?
I tried to implement it with wai-conduit but didn't figure out how finish it.
Thank you

**Comment by xenog** [comment]
Hello @anpryl,

It is actually easier to deal with HTTP than it is to do so in TCP. I don't think you need this package for HTTP JSON-RPC support. Try doing it manually. I have never tried myself.

Greetings

**Comment by alaendle** [comment]
Well.. a simple example outside of TCP might really be helpful for beginners. I'm a absolute conduit newbie, but I really have problems closing the sink channel at the right time. I'm trying to just feed json-rpc with a json string and try to receive a corresponding response.

`let sink = CL.mapM_ (\x -> $(logDebug) $ T.pack $ show x)
let source = Data.Conduit.Combinators.replicate 1 (toStrict validJsonRpcByteString)
runStderrLoggingT $ runJsonRpcT V2 False sink source srv`

If I run this the True flag of line https://github.com/xenog/json-rpc/blob/master/Network/JsonRpc/Interface.hs#L324 seems to lead to a immediate termination of the session (even before the response is created).

[Debug] session is now dead @(json-rpc-0.7.1.1-BPPsGEzLKRV5LTLDLsLhd1:Network.JsonRpc.Interface .\Network\JsonRpc\Interface.hs:156:15)

If I change the flag to false I see that the response is generated, but the call to runJsonRpcT doesn't terminate.

I believe that I'm only missing a small piece here; but unfortunately the missing link isn't obvious to me. So thanks in advance for any hint.

**Comment by xenog** [comment]
Look into the implementation of your `srv` function. If it returns then your session will be taken down. make sure it does not return before it is time to close the connection.
